//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public short Zip { get; set; }
        public Nullable<short> Question_1 { get; set; }
        public Nullable<short> Question_2 { get; set; }
        public Nullable<short> Question_3 { get; set; }
        public Nullable<short> Question_4 { get; set; }
        public Nullable<short> Question_5 { get; set; }
    }
}
